version: "3.8"
services:
  db:
    image: postgres:12
    container_name: pgsql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gigtool
      POSTGRES_PASSWORD: gigtool
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: gigtool@gigtool.com
      PGADMIN_DEFAULT_PASSWORD: gigtool
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgsql-data:
  pgadmin-data:
